# Generated by Django 4.2.16 on 2024-12-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_full_day', models.BooleanField(default=True, verbose_name='Is Full Day')),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_days', to='hrms_app.leaveapplication')),
            ],
            options={
                'unique_together': {('leave_application', 'date')},
            },
        ),
    ]
