# Generated by Django 4.2.16 on 2024-12-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0002_leaveday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='half_day_short_code',
            field=models.CharField(blank=True, help_text='Provide a short code for the leave type (optional). This must be unique if provided.', max_length=100, null=True, unique=True, verbose_name='Half Day Short Code'),
        ),
    ]
