# Generated by Django 4.2.16 on 2024-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0004_remove_holiday_tbl_holiday_is_year_643e89_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='is_early_going',
            field=models.BooleanField(default=False, help_text='Indicate if this entry is for early going regularization.', verbose_name='Is Early Going'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_late_coming',
            field=models.BooleanField(default=False, help_text='Indicate if this entry is for late coming regularization.', verbose_name='Is Late Coming'),
        ),
    ]
