# Generated by Django 4.2.16 on 2024-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0005_attendancelog_is_early_going_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='include_seconds',
            field=models.BooleanField(default=False),
        ),
    ]
