# Generated by Django 4.2.16 on 2024-12-12 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0006_deviceinformation_include_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertour',
            name='total',
            field=models.CharField(blank=True, help_text='The total duration of the tour from start date & time to end date & time', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('off_type', models.CharField(choices=[('Sunday', 'Sunday')], default='Sunday', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Off Day',
                'verbose_name_plural': 'Off Days',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
