# Generated by Django 4.2.16 on 2024-12-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0008_usertour_short_code_alter_usertour_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertour',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='usertour',
            name='tbl_user_to_status_561a11_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertour',
            name='tbl_user_to_start_d_6b4312_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertour',
            name='tbl_user_to_end_dat_5915f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertour',
            name='tbl_user_to_slug_2cd5ad_idx',
        ),
        migrations.AlterUniqueTogether(
            name='usertour',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='usertour',
            table=None,
        ),
    ]
