# Generated by Django 4.2.16 on 2024-12-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0010_alter_usertour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='Mr.', help_text='Select the salutation for the employee.', max_length=10, verbose_name='Salutation'),
        ),
    ]
