# Generated by Django 4.2.16 on 2024-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0013_lockstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockstatus',
            name='lock_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lock Month'),
        ),
        migrations.AddField(
            model_name='lockstatus',
            name='lock_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lock Year'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_limit',
            field=models.FloatField(blank=True, help_text='Set the maximum number of days that can be taken for this leave type.', null=True, verbose_name='Maximum Days Limit'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='min_days_limit',
            field=models.FloatField(blank=True, help_text='Set the minimum number of days that can be taken for this leave type.', null=True, verbose_name='Minimum Days Limit'),
        ),
    ]
