# Generated by Django 4.2.16 on 2024-12-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0014_lockstatus_lock_month_lockstatus_lock_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockstatus',
            name='from_date',
            field=models.DateField(blank=True, help_text='Provide the from date to lock the attendance', null=True, verbose_name='From Date'),
        ),
        migrations.AddField(
            model_name='lockstatus',
            name='to_date',
            field=models.DateField(blank=True, help_text='Provide the to date to lock the attendance', null=True, verbose_name='To Date'),
        ),
    ]
