# Generated by Django 4.2.16 on 2024-12-28 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0016_alter_leaveapplication_status_leavestatuspermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestatuspermission',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms_app.leavetype', verbose_name='User'),
        ),
    ]
