# Generated by Django 4.2.16 on 2024-12-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0018_alter_leavestatuspermission_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Job Anniversary', 'Job Anniversary'), ('Birthday', 'Birthday'), ('Marriage Anniversary', 'Marriage Anniversary')], max_length=100, null=True, verbose_name='Card Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishing_images/', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Wishing Card',
                'verbose_name_plural': 'Wishing Cards',
                'db_table': 'tbl_wishing_card',
            },
        ),
    ]
