# Generated by Django 4.2.16 on 2024-12-31 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0019_wishingcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetransaction',
            name='days_applied',
        ),
        migrations.RemoveField(
            model_name='leavetransaction',
            name='days_approved',
        ),
        migrations.RemoveField(
            model_name='leavetransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='leavetransaction',
            name='no_of_days_applied',
            field=models.FloatField(blank=True, help_text='Number of leave days applied for in this transaction.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Days Applied'),
        ),
        migrations.AddField(
            model_name='leavetransaction',
            name='no_of_days_approved',
            field=models.FloatField(blank=True, default=0, help_text='Number of leave days that have been approved.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Days Approved'),
        ),
        migrations.AddField(
            model_name='leavetransaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('subtract', 'Subtract')], help_text='The type of transaction (add or subtract leaves).', max_length=10, null=True, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='leavetransaction',
            name='leave_type',
            field=models.ForeignKey(blank=True, help_text='The type of leave being requested (e.g., sick leave, vacation).', null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms_app.leavetype', verbose_name='Leave Type'),
        ),
    ]
